# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 01:40
from __future__ import unicode_literals

from django.db import migrations

def create_hotels_group(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Hotel = apps.get_model('rentals', 'hotel')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    content_type = ContentType.objects.get(app_label='rentals', model='Hotel')
    permission = Permission.objects.create(codename='can_manage_hotel',
                                           name='Es gestor de hotel',
                                           content_type=content_type)

    hotel_group, created = Group.objects.get_or_create(name='hotel_managers')
    hotel_group.permissions.add(permission)
    for hotel in Hotel.objects.all():
        if hotel.owner:
            hotel.owner.groups.add(hotel_group)

class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180322_0024'),
    ]

    operations = [
        migrations.RunPython(create_hotels_group),
    ]
