# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0003_auto_20180509_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Realizada')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Es cliente del hotel')),
                ('room_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Habitaci\xf3n')),
                ('day', models.DateField(verbose_name='Dia de reserva')),
                ('time', models.TimeField(verbose_name='Hora de recogida')),
                ('duration', models.DurationField(default=0, verbose_name='Duraci\xf3n')),
                ('status', models.CharField(choices=[('accepted', 'Aceptado'), ('cancelled', 'Cancelado'), ('overdue', 'Pasado')], max_length=12)),
                ('total_amount', models.FloatField(default=0, verbose_name='Importe total')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.Hotel', verbose_name='Hotel')),
            ],
            options={
                'ordering': ['day', 'time'],
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
