# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xfamero de serie')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='rentals.Hotel', verbose_name='Hotel')),
            ],
            options={
                'ordering': ['hotel'],
                'verbose_name': 'Bici',
                'verbose_name_plural': 'Bicis',
            },
        ),
        migrations.CreateModel(
            name='RentalBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Nombre completo')),
                ('nif', models.CharField(max_length=20, verbose_name='DNI/NIF')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.Bike')),
            ],
            options={
                'verbose_name': 'Persona reserva',
                'verbose_name_plural': 'Personas reserva',
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='day_complete',
            field=models.BooleanField(default=False, verbose_name='D\xeda completo'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('cancelled', 'Cancelado'), ('overdue', 'Pasado'), ('checkin', 'Retirada'), ('checkout', 'Devuelta')], max_length=12, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='rentalbike',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='rentals.Rental', verbose_name='Reserva'),
        ),
    ]
