# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0002_auto_20180322_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color de etiqueta (c\xf3digo hexadecimal)')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('momenti/'), verbose_name='Imagen principal')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categor\xeda',
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitud')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitud')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('momenti/'), verbose_name='Imagen principal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='routes.Category', verbose_name='Categor\xeda')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='rentals.City', verbose_name='Ciudad')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Micromomento',
                'verbose_name_plural': 'Micromomentos',
            },
        ),
    ]
