# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180322_0024'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('duration', models.IntegerField(default=0, verbose_name='Duraci\xf3n de la ruta')),
                ('distance', models.IntegerField(default=0, verbose_name='Distancia de la ruta')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('momenti/'), verbose_name='Imagen principal')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_routes', to='routes.Category', verbose_name='Categor\xeda')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='rentals.Hotel', verbose_name='Hotel')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
            },
        ),
        migrations.CreateModel(
            name='HotelRoutePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('hotel_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.HotelRoute', verbose_name='Hotel')),
                ('route_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.RoutePoint', verbose_name='Micromomento')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='hotelroute',
            name='points',
            field=models.ManyToManyField(through='routes.HotelRoutePoint', to='routes.RoutePoint', verbose_name='Puntos de la ruta'),
        ),
    ]
